### ISSUE TITLE
Single contact encrypted messages fail and avatar displays as my own

### ISSUE THREAD

**Issue by distefam** [dino/dino#1110]
This behavior just started with a single contact whom I have communicated with OMEMO enabled for months successfully. 

Dino, and only Dino--there is no issue with Gajim or Snikket Android--fails to send OMEMO encrypted messages to this contact displaying a warning message that says "Unable to send message" beside the timestamp of the message. 

If I send an encrypted message via one of my other clients Dino decrypts and displays the message fine. Also, if this contact sends me a message Dino decrypts and displays the message correctly. I am also able to send non encrypted messages to this contact from Dino.

At exactly the same time that this bug presented the avatar for this user (again, and only for this user) is my own avatar. Again, this is not the case in Gajim or Snikket Android. 

I maintain the server and basic debugging there doesn't turn anything up server-side. 

The one lead I have is that the contact shows three OMEMO keys in Dino, all of which are marked as "unused" and listed under the Inactive heading. I've confirmed that two of those keys are indeed active (via my other clients). 

Is there a way to manually "reset" this contact's cached information on my computer?

**Comment by licaon-kter** [comment]
The own avatar bug was fixed iirc.

Which version of Dino do you have? Which OS? Can you use a build from OBS?

**Comment by distefam** [comment]
I am using Dino version 0.2.1 on FreeBSD 13.0-RELEASE. I could build from source if that is what you mean by OBS?

**Comment by licaon-kter** [comment]
No, OBS is https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino :)

**Comment by distefam** [comment]
I'll try that later today. I haven't installed any Linux binaries directly on this machine yet. 

I also had this contact change her avatar and the update is reflected in Dino now. However, the OMEMO issue persists.

**Comment by licaon-kter** [comment]
No, I meant it's an Linux only build thing. :)

**Comment by distefam** [comment]
I know, it's possible to [install Linux binaries on FreeBSD](https://docs.freebsd.org/en/books/handbook/linuxemu/), however.

**Comment by distefam** [comment]
@licaon-kter Ran into some issues getting the RPM to install properly. Any other ideas?

**Comment by distefam** [comment]
Some more information on this. It appears that the contact for which this issue presents is the only one in my list who uses Monal for the Mac (in addition to Snikket iOS). When the issue presents, Monal (5.0.1) is either the only client listed in the hover popup in Dino or the only active (green) one.

**Comment by hirusi** [comment]
I have the exact same issue -- except I also can't text this person. For the brief window I see _their_ avatar, I can quickly send a message, and it'll go through. Once my own avatar shows, all communication is impossible via Dino.

They are using Gajim on Windows. But have used Monal and Siskin/Snikket iOS in the past.

**Comment by distefam** [comment]
Glad to hear I'm not the only one. Hopefully, we can figure out a way to reliably reproduce this bug. I upgraded to Dino 0.2.2 a few days ago and the issue is still present.

**Comment by distefam** [comment]
Blocking and unblocking the problematic user account does have the effect of replacing their avatar with the correct one, but must do this every time I open Dino. Any update on this?

**Comment by fiaxh** [comment]
The OMEMO contact list and avatars are both transmitted through PEP messages. It sounds like Dino thinks that the PEP messages from your own account are coming from your contact. Blocking and unblocking your contact results in your contact's PEP messages being resent. However, I have no good theory yet as to _why_ Dino would wrongly assign your PEP messages to your contact.

Could you give me a few logs, such that I can look for something unusual? To generate the logs, please start Dino with
```
G_MESSAGES_DEBUG=libdino,xmpp-vala,OMEMO ./build/dino --print-xmpp="message[from=your-contact@example.com]|message[from=you@example.com]|message[type=error]|iq[type=error]"
```
and replace `your-contact@example.com` and `you@example.com` with your contact's JID and your JID, respectively. You might want to obfuscate any JIDs before posting the log, while keeping them distinguishable.

**Comment by engenteur** [comment]
Hopefully it can help... And I didn't obfuscate too much... I have the same problem with a contact who used Monal client once. His profile picture becomes mines and it's impossible to send him OMEMO encrypted messages :(

[dino-1110.log](https://github.com/dino/dino/files/7835290/dino-1110.log)

**Comment by fiaxh** [comment]
I pushed a commit that might fix this issue f2ef2bcfe7f3e5d1449285c1517df703af1221a4. Could one of you please test it and report if it indeed fixes the problem? You can either self-compile Dino or use our nightly [OBS repositories](https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino).

If it works, I'd be interested in some logs again, because it might be that some other client sends strange stanzas around. Please start Dino normally from the console and look out for lines that say `WARNING [,,,] Got a PEP message from a full JID (user@example.com/resource): [some XML] and post those warnings here. If you obfuscate the logs, please have a look at the resource part of the full JID. yourself: Does it name a client?

**Comment by engenteur** [comment]
I compiled a fresh Dino and my problem magically disappeared ! Thank you @fiaxh !

What is strange in the logs is that the warning that showed up doesn't concern a user with who I was having problems... The warning actually concerns a user that I just added today on the server... The only client that this account ever logged in is a beta (TestFlight) version of Snikket iOS.

[dino-1110-newer.log](https://github.com/dino/dino/files/7842083/dino-1110-newer.log)
