### ISSUE TITLE
[UI] Window not resizeable by mouse and no shadow drawn

### ISSUE THREAD

**Issue by Echolon** [dino/dino#725]
Hi,

unfortunately it's not possible to resize Dino. A shadow of the window is also not drawn anymore. Both doesn't work for **any** border along the Dino window.

Dino: 0.0~git639.20200122.3b0a27e (which is the build from the 21.01.2020 https://github.com/dino/dino/commit/3b0a27e14bcce3a06f0ac1199bb0acb5c3434444)

Kubuntu 18.04
KDE Plasma Version: 5.12.9
KDE Frameworks Version: 5.47.0
Qt version: 5.9.5

Here are some screens for you, both problems should be seen.
If I can provide addititional information, please ask and tell me how to aquire if not obivious.

<img src="https://user-images.githubusercontent.com/29168011/73016081-7d934a80-3e1d-11ea-9937-777d84f2ed6f.png" width="529">

Cheers & :heart: Dino

**Comment by ericschdt** [comment]
This is fixed with Plasma 5.18:

> full support for the GTK_FRAME_EXTENTS_ protocol, which hugely improves the user experience for running GTK apps that use client-side decoration headerbars! This includes GNOME apps and an increasing number of 3rd-party GTK apps too. In particular, these apps now display window shadows and have proper resize areas without needing to use a thick border. 

https://pointieststick.com/2019/11/30/this-week-in-kde-gtk-csd-support-and-more/

**Comment by Echolon** [comment]
@ericschdt Ah, yes, I just remembered.

So this is a KDE issue?

**Comment by ericschdt** [comment]
> @ericschdt Ah, yes, I just remembered.
> 
> So this is a KDE issue?

Kind of. Though, the Dino devs don't need to do anything here. All you need is to upgrade in April. :)

**Comment by C0D3D3V** [comment]
I have KDE Plasma 5.20.3-1. This issue still exists and is really annoying
